baseURL = "https://jiwooblog.netlify.app/"
title = "Hugo Zdoc Theme"
theme = "hugo-theme-zdoc"

defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

copyright = "&copy;{year}, All Rights Reserved"
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"] 
#publishDir = "docs"
#github -> Settings -> Options -> Github pages -> Source를 docs로 바꾸면 github.io로 디자인 가능
#그런데 이렇게 하면, netlify에서 site setting도 public->docsf로 바꿔줘야 할 것 같긴 함.

#highlightjsTheme = "A 11 Y Dark"

googleAnalytics = ""

disableKinds = ["taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    lineNoStart = 1
    noClasses = false  # 이게 뭔가 핵심인거 같은데ㅠㅠ
#    style = "fruity"

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
  
[params]
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"
